=== Javieraeros/LenguajedeMarcas/Schema/fichas_con_enumerado.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/fichas_con_enumerado" 
	xmlns="http://www.example.org/fichas_con_enumerado" 
	elementFormDefault="qualified">
	<xs:element name="fichas">
		<xs:complexType>
			<xs:complexContent>
				<xs:restriction base="xs:anyType">
					<xs:sequence>
						<xs:element name="ficha" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:restriction base="xs:anyType">
										<xs:sequence>
											<xs:element name="nombre" type="xs:string"/>
											<xs:element name="apellido1" type="xs:string"/>
											<xs:element name="apellido2" type="xs:string"/>
											<xs:element name="email" type="tipo_email"  minOccurs="0" maxOccurs="2" />
											<xs:element name="direccion" type="tipo_direccion" minOccurs="0" maxOccurs="3"/>
										</xs:sequence>
										<xs:attribute name="categoria" type="tipo_cat" use="required"/>
										<xs:attribute name="zona" type="tipo_zona" use="optional"/>
									</xs:restriction>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:restriction>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipo_email">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z])+@([a-zA-Z])+.com"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="tipo_direccion">
		<xs:complexContent>
			<xs:restriction base="xs:anyType">
				<xs:sequence>
					<xs:element name="calle" type="xs:string"/>
					<xs:element name="piso" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="letra" minOccurs="0" maxOccurs="1">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="[a-zA-Z]"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="codigo_postal">
						<xs:simpleType>
							<xs:restriction base="xs:int">
								<xs:minInclusive value="1000"/>
								<xs:maxInclusive value="9999"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="ciudad" type="xs:string"/>
					<xs:element name="pais" type="xs:string"/>
				</xs:sequence>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="tipo_cat">
		<xs:restriction base="xs:string">
			<xs:pattern value="empresa|particular|agente_comercial"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipo_zona">
		<xs:restriction base="xs:string">
			<xs:pattern value="Centro|Macarena|Remedios"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Javieraeros/LenguajedeMarcas/Schema/fichas_con_enumerado1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:fichas xmlns:p="http://www.example.org/fichas_con_enumerado" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/fichas_con_enumerado fichas_con_enumerado.xsd ">
  <p:ficha categoria="" zona="">
    <p:nombre>p:nombre</p:nombre>
    <p:apellido1>p:apellido1</p:apellido1>
    <p:apellido2>p:apellido2</p:apellido2>
    <p:email>p:email</p:email>
    <p:direccion>
      <p:calle>p:calle</p:calle>
      <p:piso>p:piso</p:piso>
      <p:letra>p:letra</p:letra>
      <p:codigo_postal>0</p:codigo_postal>
      <p:ciudad>p:ciudad</p:ciudad>
      <p:pais>p:pais</p:pais>
    </p:direccion>
  </p:ficha>
</p:fichas>

=== Javieraeros/LenguajedeMarcas/Schema/fichas_con_enumerado.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:fichas xmlns:p="http://www.example.org/fichas_con_enumerado" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/fichas_con_enumerado fichas_con_enumerado.xsd ">
  <p:ficha categoria="empresa">
    <p:nombre>Javier</p:nombre>
    <p:apellido1>Rui</p:apellido1>
    <p:apellido2>Rodr√≠guez</p:apellido2>
    <p:email>Javier@a.com</p:email>
    <p:email>Pajarrurro@gmail.com</p:email>
    <p:direccion>
      <p:calle>p:calle</p:calle>
      <p:piso>p:piso</p:piso>
      <p:letra>z</p:letra>
      <p:codigo_postal>1001</p:codigo_postal>
      <p:ciudad>p:ciudad</p:ciudad>
      <p:pais>p:pais</p:pais>
    </p:direccion>
  </p:ficha>
  <p:ficha categoria="empresa" zona="Macarena">
    <p:nombre>p:nombre</p:nombre>
    <p:apellido1>p:apellido1</p:apellido1>
    <p:apellido2>p:apellido2</p:apellido2>
    <p:direccion>
      <p:calle>p:calle</p:calle>
      <p:codigo_postal>4774</p:codigo_postal>
      <p:ciudad>p:ciudad</p:ciudad>
      <p:pais>p:pais</p:pais>
    </p:direccion>
  </p:ficha>
</p:fichas>
