=== Javieraeros/LenguajedeMarcas/DTD/atomos.dtd
<!--Definir un DTD (atomos.dtd) y un fichero XML (atomos.xml) válido con respecto a aquel, de tal
forma que contenga un listado de uno o más átomos donde cada átomo tiene las siguientes
características:
- un atributo estado
- un elemento nombre
- un elemento símbolo
- un elemento número atómico
- un elemento peso atómico
- un elemento punto_ebullicion con un atributo unidades
- un elemento densidad con un atributo unidades-->
<!ELEMENT TABLA_PERIODICA (ATOMO+)>
<!ELEMENT ATOMO (NOMBRE,SIMBOLO,NUMERO_ATOMICO,PESO_ATOMICO,PUNTO_EBULLICION,DENSIDAD)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT SIMBOLO (#PCDATA)>
<!ELEMENT NUMERO_ATOMICO (#PCDATA)>
<!ELEMENT PESO_ATOMICO (#PCDATA)>
<!ELEMENT PUNTO_EBULLICION (#PCDATA)>
<!ELEMENT DENSIDAD (#PCDATA)>


<!ATTLIST ATOMO ESTADO CDATA #REQUIRED>
<!ATTLIST PUNTO_EBULLICION UNIDADES CDATA #REQUIRED>
<!ATTLIST DENSIDAD UNIDADES CDATA #REQUIRED>

=== Javieraeros/LenguajedeMarcas/DTD/atomos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TABLA_PERIODICA SYSTEM "atomos.dtd">
<TABLA_PERIODICA>
	<ATOMO ESTADO="GAS">
		<NOMBRE>Hidr√≥geno</NOMBRE>
		<SIMBOLO>H</SIMBOLO>
		<NUMERO_ATOMICO>1</NUMERO_ATOMICO>
		<PESO_ATOMICO>1.00794</PESO_ATOMICO>
		<PUNTO_EBULLICION UNIDADES="KELVIN">20.28</PUNTO_EBULLICION>
		<DENSIDAD UNIDADES="gramos/cc">0,0899</DENSIDAD>
	</ATOMO>
	<ATOMO ESTADO="LIQUIDO">
		<NOMBRE>Mercurio</NOMBRE>
		<SIMBOLO>Hg</SIMBOLO>
		<NUMERO_ATOMICO>80</NUMERO_ATOMICO>
		<PESO_ATOMICO>200.59</PESO_ATOMICO>
		<PUNTO_EBULLICION UNIDADES="KELVIN">629.88</PUNTO_EBULLICION>
		<DENSIDAD UNIDADES="kg/m^3">13579.04</DENSIDAD>
	</ATOMO>
	<ATOMO ESTADO="SOLIDO">
		<NOMBRE>Oro</NOMBRE>
		<SIMBOLO>Au</SIMBOLO>
		<NUMERO_ATOMICO>79</NUMERO_ATOMICO>
		<PESO_ATOMICO>196.97</PESO_ATOMICO>
		<PUNTO_EBULLICION UNIDADES="KELVIN">3129</PUNTO_EBULLICION>
		<DENSIDAD UNIDADES="kg/m^3">19300</DENSIDAD>
	</ATOMO>
	
</TABLA_PERIODICA>
